#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "C:/develop/pechblenda/urxnium/urxnium-cli/dist/index.js" "$@"
  ret=$?
else
  node  "C:/develop/pechblenda/urxnium/urxnium-cli/dist/index.js" "$@"
  ret=$?
fi
exit $ret
